config/routes.rb
Chan::Application.routes.draw do
  resources :users
  resources :enum_values
  resources :form_properties
  resources :tasks
  resources :sessions
  resources :v_messages

  root 'tasks#index'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :api do
    resources :tasks
    get 'task_by_taskid', to: 'tasks#show_by_taskid', as: 'task_by_taskid'
    post 'task_by_taskid', to: 'tasks#update_by_taskid', as: 'update_by_taskid'
    resources :v_messages
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :taskid, presence: true
  #validates :url, presence: true
  #validates :assignee, presence: true
  
  has_many :form_properties, dependent: :destroy
  accepts_nested_attributes_for :form_properties, :allow_destroy => true
end

app/controllers/api/tasks_controller.rb
module Api
  class TasksController < ApplicationController
    respond_to :json
    #before_action :authenticate_token!

    def index
      @tasks = Task.all
      respond_with @tasks
    end

    def create
      @task = Task.create(task_params)
      sms_content = task_params[:description].to_s + " - Please dial " + VUM_USSD_CHANNEL
      sms_params = {content: sms_content, msisdn: task_params[:assignee]}

      SendSms.build.call(sms_params)
      
      respond_with @task
    end

    def update_by_taskid
      @task = Task.find_by_taskid(task_params[:taskid])
      @task.update_attributes!(task_params)
      respond_with @task
    end

    def show_by_taskid
      @task = Task.find_by_taskid(params[:id])
      respond_with @task
    end

    def show
      @task = Task.find(params[:id])
      respond_with @task
    end

    private
    
    def task_params
      params.require(:task).permit(:taskid, :url, :assignee, :name, :description, :processed, :in_progress, :form_properties_attributes => [:formpropid, :name, :formproptype, :value, :writeable, :enum_values_attributes => [:enumvalid, :name]])
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!

  def index
    @tasks = Task.all.order("created_at DESC")
  end

  def show
    @task = Task.includes(form_properties: [:enum_values]).find(params[:id])
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">
       <%= task.assignee %> - <%= task.name %>
      </h3>
   </div>
  <div class="panel-body">
   <form role="form">
     <div class="form-group">
       <label for="id">Id:</label>
       <input type="text" class="form-control" id="id" placeholder="<%= task.id %>">
     </div>
     <div class="form-group">
       <label for="pwd">TaskId:</label>
       <input type="text" class="form-control" id="taskid" placeholder="<%= task.taskid %>">
     </div>
     <div class="form-group">
       <label for="pwd">URL:</label>
       <input type="text" class="form-control" id="url" placeholder="<%= task.url %>">
     </div>
     <div class="form-group">
       <label for="pwd">Assignee:</label>
       <input type="text" class="form-control" id="assignee" placeholder="<%= task.assignee %>">
     </div>
     <div class="form-group">
       <label for="pwd">Name:</label>
       <input type="text" class="form-control" id="name" placeholder="<%= task.name %>">
     </div>
     <div class="form-group">
       <label for="pwd">Description:</label>
       <input type="text" class="form-control" id="description" placeholder="<%= task.description %>">
     </div>
     <div class="form-group">
       <label for="pwd">Processed:</label>
       <input type="text" class="form-control" id="processed" placeholder="<%= task.processed %>">
     </div>
     <div class="form-group">
       <label for="pwd">In Progress:</label>
       <input type="text" class="form-control" id="in_progress" placeholder="<%= task.in_progress %>">
     </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="page-header">
    <h1>Tasks</h1>
</div>
<%= render @tasks %>

app/views/tasks/show.html.erb
<div class="page-header">
  <h1>Task</h1>
</div>

<%= render @task %>

<h3>Form Properties</h3>
<%= render @task.form_properties %>

<%= link_to "Home", tasks_path, class: "btn btn_default" %>

app/views/tasks/task.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">
       <%= task.name %>
      </h3>
    </div>

 <div class="panel-body">
    <p><em>Assignee <%= task.assignee %></em></p>

    <%= task.id %>
    <%= task.url %>
    <%= task.name %>
    <%= task.description %>
  </div>
</div>