config/routes.rb
Chan::Application.routes.draw do
  resources :users
  resources :enum_values
  resources :form_properties
  resources :tasks
  resources :sessions
  resources :v_messages

  root 'tasks#index'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :api do
    resources :tasks
    get 'task_by_taskid', to: 'tasks#show_by_taskid', as: 'task_by_taskid'
    post 'task_by_taskid', to: 'tasks#update_by_taskid', as: 'update_by_taskid'
    resources :v_messages
  end

end

app/models/v_message.rb
class VMessage < ActiveRecord::Base
end

app/controllers/api/v_messages_controller.rb
module Api
  class VMessagesController < ApplicationController
    respond_to :json
    #before_action :authenticate_token!

    def index
      @v_messages = VMessage.all
      respond_with @v_messages
    end

    def create
      vmsg_params = v_message_params

      if vmsg_params[:direction].nil?
        vmsg_params[:direction] = "fromVum"
      end

      @v_message = VMessage.create(vmsg_params)
      
      if vmsg_params[:transport_type] == "ussd"
        ConverseUssd.build.call(vmsg_params)
      elsif vmsg_params[:transport_type] == "sms" && vmsg_params[:direction] == "fromVum"
        ReceiveSms.build.call(vmsg_params)
      elsif vmsg_params[:transport_type] == "sms" && vmsg_params[:direction] == "fromAct"
        SendSms.build.call({msisdn: vmsg_params[:to_addr], content: vmsg_params[:content]})
      end

      respond_with @v_message
    end

    private

    def v_message_params
      params.require(:v_message).permit(:message_id, :in_reply_to, :content, :session_event, :to_addr, :to_addr_type, :from_addr, :from_addr_type, :transport_name, :transport_type, :direction)
    end

  end
end

app/controllers/v_messages_controller.rb
class VMessagesController < ApplicationController
  before_action :set_v_message, only: [:show, :edit, :update, :destroy]

  # GET /v_messages
  # GET /v_messages.json
  def index
    @v_messages = VMessage.all
  end

  # GET /v_messages/1
  # GET /v_messages/1.json
  def show
  end

  # GET /v_messages/new
  def new
    @v_message = VMessage.new
  end

  # GET /v_messages/1/edit
  def edit
  end

  # POST /v_messages
  # POST /v_messages.json
  def create
    @v_message = VMessage.new(v_message_params)

    respond_to do |format|
      if @v_message.save
        format.html { redirect_to @v_message, notice: 'V message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @v_message }
      else
        format.html { render action: 'new' }
        format.json { render json: @v_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /v_messages/1
  # PATCH/PUT /v_messages/1.json
  def update
    respond_to do |format|
      if @v_message.update(v_message_params)
        format.html { redirect_to @v_message, notice: 'V message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @v_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /v_messages/1
  # DELETE /v_messages/1.json
  def destroy
    @v_message.destroy
    respond_to do |format|
      format.html { redirect_to v_messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_v_message
      @v_message = VMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def v_message_params
      params.require(:v_message).permit(:message_id, :in_reply_to, :content, :session_event, :to_addr, :to_addr_type, :from_addr, :from_addr_type, :transport_name, :transport_type)
    end
end

app/helpers/v_messages_helper.rb
module VMessagesHelper
end

app/views/v_messages/_form.html.erb
<%= form_for(@v_message) do |f| %>
  <% if @v_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@v_message.errors.count, "error") %> prohibited this v_message from being saved:</h2>

      <ul>
      <% @v_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message_id %><br>
    <%= f.text_field :message_id %>
  </div>
  <div class="field">
    <%= f.label :in_reply_to %><br>
    <%= f.text_field :in_reply_to %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :session_event %><br>
    <%= f.text_field :session_event %>
  </div>
  <div class="field">
    <%= f.label :to_addr %><br>
    <%= f.text_field :to_addr %>
  </div>
  <div class="field">
    <%= f.label :to_addr_type %><br>
    <%= f.text_field :to_addr_type %>
  </div>
  <div class="field">
    <%= f.label :from_addr %><br>
    <%= f.text_field :from_addr %>
  </div>
  <div class="field">
    <%= f.label :from_addr_type %><br>
    <%= f.text_field :from_addr_type %>
  </div>
  <div class="field">
    <%= f.label :transport_name %><br>
    <%= f.text_field :transport_name %>
  </div>
  <div class="field">
    <%= f.label :transport_type %><br>
    <%= f.text_field :transport_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/v_messages/edit.html.erb
<h1>Editing v_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @v_message %> |
<%= link_to 'Back', v_messages_path %>

app/views/v_messages/index.html.erb
<h1>Listing v_messages</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>In reply to</th>
      <th>Content</th>
      <th>Session event</th>
      <th>To addr</th>
      <!-- <th>To addr type</th> -->
      <th>From addr</th>
      <!-- <th>From addr type</th> -->
      <!-- <th>Transport name</th> -->
      <th>Transport type</th>
      <th>Direction</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @v_messages.each do |v_message| %>
      <tr>
        <td><%= v_message.message_id %></td>
        <td><%= v_message.in_reply_to %></td>
        <td><%= v_message.content %></td>
        <td><%= v_message.session_event %></td>
        <td><%= v_message.to_addr %></td>
        <!-- <td><%= v_message.to_addr_type %></td> -->
        <td><%= v_message.from_addr %></td>
        <!-- <td><%= v_message.from_addr_type %></td> -->
        <!-- <td><%= v_message.transport_name %></td> -->
        <td><%= v_message.transport_type %></td>
        <td><%= v_message.direction %></td>
        <td><%= link_to 'Show', v_message %></td>
        <td><%= link_to 'Edit', edit_v_message_path(v_message) %></td>
        <td><%= link_to 'Destroy', v_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New V message', new_v_message_path %>

app/views/v_messages/new.html.erb
<h1>New v_message</h1>

<%= render 'form' %>

<%= link_to 'Back', v_messages_path %>

app/views/v_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @v_message.message_id %>
</p>

<p>
  <strong>In reply to:</strong>
  <%= @v_message.in_reply_to %>
</p>

<p>
  <strong>Content:</strong>
  <%= @v_message.content %>
</p>

<p>
  <strong>Session event:</strong>
  <%= @v_message.session_event %>
</p>

<p>
  <strong>To addr:</strong>
  <%= @v_message.to_addr %>
</p>

<p>
  <strong>To addr type:</strong>
  <%= @v_message.to_addr_type %>
</p>

<p>
  <strong>From addr:</strong>
  <%= @v_message.from_addr %>
</p>

<p>
  <strong>From addr type:</strong>
  <%= @v_message.from_addr_type %>
</p>

<p>
  <strong>Transport name:</strong>
  <%= @v_message.transport_name %>
</p>

<p>
  <strong>Transport type:</strong>
  <%= @v_message.transport_type %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @v_message.direction %>
</p>

<%= link_to 'Edit', edit_v_message_path(@v_message) %> |
<%= link_to 'Back', v_messages_path %>